# Starship Configuration
# Based on Gruvbox Rainbow preset, adapted to use terminal colors
# https://starship.rs/presets/gruvbox-rainbow

format = """
[](red)\
$os\
$username\
[](bg:yellow fg:red)\
$directory\
[](fg:yellow bg:cyan)\
$git_branch\
$git_status\
[](fg:cyan bg:blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$julia\
[](fg:blue bg:bright-black)\
$docker_context\
$conda\
$pixi\
[](fg:bright-black bg:black)\
$time\
[ ](fg:black)\
$line_break$character"""

[os]
disabled = false
style = "bg:red fg:bright-white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"

[username]
show_always = false
style_user = "bg:red fg:bright-white"
style_root = "bg:red fg:bright-white"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:black bg:cyan)]($style)'

[git_status]
style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:black bg:cyan)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[cpp]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[java]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[julia]
symbol = "ஃ"
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bright-white bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:bright-black"
format = '[[ $symbol( $context) ](fg:cyan bg:bright-black)]($style)'

[conda]
style = "bg:bright-black"
format = '[[ $symbol( $environment) ](fg:cyan bg:bright-black)]($style)'

[pixi]
style = "bg:bright-black"
format = '[[ $symbol( $version)( $environment) ](fg:bright-white bg:bright-black)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:black"
format = '[[  $time ](fg:bright-white bg:black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
