# Minimal starship prompt

format = '\[$hostname$directory$git_branch$git_status\] $character'
add_newline = true
scan_timeout = 10
command_timeout = 200

[hostname]
format = '$hostname '
ssh_only = true
trim_at = '.'

[directory]
format = '$path'
style = 'cyan'
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = ' $branch'
style = 'green'

[git_status]
format = ' $all_status$ahead_behind'
style = 'yellow'
ignore_submodules = true
ahead = '>'
behind = '<'
diverged = '<>'
conflicted = '='
untracked = '?'
stashed = '*'
modified = '!'
staged = '+'
renamed = 'r'
deleted = 'x'

[character]
success_symbol = ''
error_symbol = '[!](red)'
